#!/usr/bin/env bash
# Behavior tests for the pinned pstack importer and generated brief catalog.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

TMP_ROOT=$(fm_test_tmproot fm-pstack-sync)
SOURCE="$TMP_ROOT/source"
DEST="$TMP_ROOT/dest"
CONFIG="$TMP_ROOT/fixture-lock.json"
mkdir -p "$SOURCE/pstack/skills/fixture/references" "$SOURCE/pstack/skills/excluded" "$DEST"

PIN=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["upstream"]["commit"])' "$ROOT/bin/fm-pstack-sync.lock.json")
printf '%s\n' "$PIN" > "$SOURCE/.pstack-source-commit"
cat > "$SOURCE/pstack/skills/fixture/SKILL.md" <<'EOF'
---
name: fixture
description: A small fixture skill used by the executable importer tests.
disable-model-invocation: true
model: cursor-test-model
---

# Fixture

The body is local fixture content, not an assertion of upstream prose.
EOF
printf '%s\n' '# Fixture reference' 'A reference file must be copied.' > "$SOURCE/pstack/skills/fixture/references/note.md"
printf '%s\n' 'excluded' > "$SOURCE/pstack/skills/excluded/SKILL.md"

python3 - "$ROOT/bin/fm-pstack-sync.lock.json" "$CONFIG" <<'PY'
import json
import sys

source, destination = sys.argv[1:]
lock = json.load(open(source, encoding="utf-8"))
lock["allowlist"] = [{
    "name": "fixture",
    "tier": 2,
    "source": "skills/fixture",
    "include": ["SKILL.md", "references/**"],
}]
lock["excluded_components"] = ["excluded"]
lock["replacements"] = []
lock["post_replacements"] = []
lock["compatibility"]["skill_notes"] = {}
lock["index"] = {
    "path": "generated-index.md",
    "preamble": ["Fixture catalog."],
    "groups": [{"title": "Fixture", "skills": ["fixture"]}],
    "footer": [],
    "brief_budget": {"baseline_words": 10, "max_words": 100, "catalog_max_words": 50},
}
with open(destination, "w", encoding="utf-8") as handle:
    json.dump(lock, handle, indent=2)
    handle.write("\n")
PY

run_sync() {
  "$ROOT/bin/fm-pstack-sync.sh" --root "$DEST" --config "$CONFIG" --source "$SOURCE" "$@"
}

test_import_converts_frontmatter_and_allowlist() {
  local out rc
  out=$(run_sync 2>&1); rc=$?
  expect_code 0 "$rc" "fixture import should succeed: $out"
  assert_present "$DEST/.agents/skills/fixture/SKILL.md" "allowlisted skill was not imported"
  assert_present "$DEST/.agents/skills/fixture/references/note.md" "allowlisted reference was not imported"
  assert_absent "$DEST/.agents/skills/excluded/SKILL.md" "excluded skill was imported"
  assert_grep 'user-invocable: false' "$DEST/.agents/skills/fixture/SKILL.md" \
    "Cursor invocation frontmatter was not converted"
  assert_grep 'internal: true' "$DEST/.agents/skills/fixture/SKILL.md" \
    "internal Firstmate metadata was not added"
  assert_no_grep 'disable-model-invocation' "$DEST/.agents/skills/fixture/SKILL.md" \
    "Cursor-only frontmatter was retained"
  assert_no_grep 'cursor-test-model' "$DEST/.agents/skills/fixture/SKILL.md" \
    "Cursor-only model configuration was retained"
  assert_grep 'fixture' "$DEST/generated-index.md" "generated catalog omitted the imported skill"
  assert_no_grep 'The body is local fixture content' "$DEST/generated-index.md" \
    "generated catalog injected the full skill body"
  mkdir -p "$DEST/.agents/skills/omitted"
  printf '%s\n' 'keep this local skill' > "$DEST/.agents/skills/omitted/SKILL.md"
  run_sync --check >/dev/null 2>&1 || fail "check should ignore omitted local skills"
  assert_present "$DEST/.agents/skills/omitted/SKILL.md" "sync deleted an omitted local skill"
  pass "fm-pstack-sync: allowlist and frontmatter conversion work"
}

test_pin_and_conflict_guards() {
  local out rc original_hash rerun_hash
  printf '%s\n' 'wrong-pin' > "$SOURCE/.pstack-source-commit"
  out=$(run_sync 2>&1); rc=$?
  expect_code 1 "$rc" "wrong source pin must fail: $out"
  assert_contains "$out" "is not locked commit" "wrong source pin error was not explicit"
  printf '%s\n' "$PIN" > "$SOURCE/.pstack-source-commit"

  original_hash=$(find "$DEST" -type f -print0 | sort -z | xargs -0 sha256sum)
  out=$(run_sync --check 2>&1); rc=$?
  expect_code 0 "$rc" "idempotent check should pass: $out"
  rerun_hash=$(find "$DEST" -type f -print0 | sort -z | xargs -0 sha256sum)
  [ "$original_hash" = "$rerun_hash" ] || fail "same pinned sync changed generated bytes"

  printf '%s\n' 'local divergent adaptation' >> "$DEST/.agents/skills/fixture/SKILL.md"
  out=$(run_sync 2>&1); rc=$?
  expect_code 2 "$rc" "divergent generated output must stop: $out"
  assert_contains "$out" "review the diff" "conflict report did not request review"
  assert_grep 'local divergent adaptation' "$DEST/.agents/skills/fixture/SKILL.md" \
    "conflict detection overwrote the local adaptation"
  out=$(run_sync --accept-reviewed 2>&1); rc=$?
  expect_code 0 "$rc" "explicit reviewed acceptance should resolve the conflict: $out"
  assert_no_grep 'local divergent adaptation' "$DEST/.agents/skills/fixture/SKILL.md" \
    "reviewed acceptance did not regenerate the output"
  pass "fm-pstack-sync: pin, idempotence, and conflict guards work"
}

test_script_parses() {
  local out rc
  out=$(bash -n "$ROOT/bin/fm-pstack-sync.sh" 2>&1); rc=$?
  expect_code 0 "$rc" "sync tool must parse: $out"
  [ -z "$out" ] || fail "sync tool parse emitted unexpected output: $out"
  pass "fm-pstack-sync: shell wrapper parses"
}

test_script_parses
test_import_converts_frontmatter_and_allowlist
test_pin_and_conflict_guards
